mode = "dark"
accent = "#D0A267"
selection = "#514032"
selection_background = "#514032"
selection_foreground = "#E5DCCC"
muted = "#A2978D"
background = "#161414"
dark_background = "#100E0E"
darker_background = "#0B0909"
lighter_background = "#262120"
foreground = "#E5DCCC"
dark_foreground = "#A2978D"
light_foreground = "#CBBFAE"
bright_foreground = "#F3EBDD"
red = "#D1847C"
yellow = "#D8B77F"
orange = "#CD986D"
green = "#ACB597"
cyan = "#8EB6B1"
blue = "#9DAEBF"
magenta = "#BC8F9D"
brown = "#AE8C71"
bright_red = "#E4A099"
bright_yellow = "#EBCD9C"
bright_green = "#C6CDB4"
bright_cyan = "#B1D0C9"
bright_blue = "#BECBDC"
bright_magenta = "#D4ACBA"
